name: CI Tests

on:
  push:
    branches:
      - main
    paths:
      - project/**

  workflow_dispatch:
    
jobs:
  test:
    runs-on: ubuntu-latest

    steps: 
      - name: Check out Code 
        uses: actions/checkout@v4
        with:
          path: main

      - name: Python Setup
        uses: actions/setup-python@v4
        with: 
        python-version: 3.9

      - name: Install dependencies
        run: | 
              python -m pip install --upgrade pip
              pip install pytest pandas
            
      - name: Make File executable
        run: |
              ls 
              chmod +x main/project/tests.sh 

      - name: Run Tests
        run: main/project/tests.sh 
